import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import api from '../services/api';

const Home = () => {
    const [categories, setCategories] = useState([]);

    useEffect(() => {
        const fetchCategories = async () => {
            try {
                const res = await api.get('/structure/categories');
                setCategories(res.data);
            } catch (error) {
                console.error("Failed to fetch categories", error);
            }
        };
        fetchCategories();
    }, []);

    return (
        <div className="space-y-12 pb-12">
            {/* Hero Section */}
            <section className="bg-gradient-to-r from-primary to-indigo-700 text-white py-20 px-4">
                <div className="max-w-4xl mx-auto text-center">
                    <h1 className="text-4xl md:text-5xl font-extrabold mb-6">Master Your Exams with AI</h1>
                    <p className="text-lg md:text-xl text-indigo-100 mb-8">
                        Unlimited practice, AI-driven explanations, and group competitions.
                    </p>
                    <Link to="/practice" className="bg-white text-primary font-bold py-3 px-8 rounded-full shadow-lg hover:bg-gray-100 transition transform hover:-translate-y-1">
                        Start Practicing
                    </Link>
                </div>
            </section>

            {/* Categories Slider (Horizontal Scroll) */}
            <section className="max-w-7xl mx-auto px-4">
                <h2 className="text-2xl font-bold mb-6 text-gray-800">Categories</h2>
                <div className="flex space-x-6 overflow-x-auto pb-6 scrollbar-hide">
                    {categories.map((cat) => (
                        <div key={cat.id} className="min-w-[160px] md:min-w-[200px] bg-white rounded-xl shadow-md p-6 text-center hover:shadow-xl transition cursor-pointer border border-gray-100">
                            {/* Placeholder Icon */}
                            <div className="w-16 h-16 bg-indigo-100 rounded-full mx-auto mb-4 flex items-center justify-center text-2xl">
                                📚
                            </div>
                            <h3 className="font-semibold text-gray-700">{cat.name}</h3>
                        </div>
                    ))}
                    {categories.length === 0 && (
                        <div className="text-gray-500">Loading categories...</div>
                    )}
                </div>
            </section>

            {/* Features Grid */}
            <section className="max-w-7xl mx-auto px-4">
                <h2 className="text-2xl font-bold mb-6 text-gray-800">Why ExamRedy?</h2>
                <div className="grid md:grid-cols-3 gap-8">
                    <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
                        <div className="text-4xl mb-4">🤖</div>
                        <h3 className="text-xl font-bold mb-2">AI-Powered</h3>
                        <p className="text-gray-600">Get instant explanations and personalized question sets generated by advanced AI.</p>
                    </div>
                    <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
                        <div className="text-4xl mb-4">👥</div>
                        <h3 className="text-xl font-bold mb-2">Group Mode</h3>
                        <p className="text-gray-600">Compete with friends in real-time. Join sessions and climb the leaderboard.</p>
                    </div>
                    <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
                        <div className="text-4xl mb-4">⚡</div>
                        <h3 className="text-xl font-bold mb-2">Instant Results</h3>
                        <p className="text-gray-600">Track your performance with detailed analytics and history tracking.</p>
                    </div>
                </div>
            </section>
        </div>
    );
};

export default Home;
